version: '3.9'
services:
  dataset-uploader-api:
    build:
      context: ./dataset-uploader-api
    ports:
      - "8001:8080"
    volumes:
      - ./integration_tests:/app/integration_tests
      - ./data:/app/data
    networks:
      - ai-net
  data-profiler-api:
    build:
      context: ./data-profiler-api
    ports:
      - "8002:8080"
    volumes:
      - ./integration_tests:/app/integration_tests
      - ./data:/app/data
    networks:
      - ai-net
    depends_on:
      - dataset-uploader-api
  data-cleaner-api:
    build:
      context: ./data-cleaner-api
    ports:
      - "8003:8080"
    volumes:
      - ./integration_tests:/app/integration_tests
      - ./data:/app/data
    networks:
      - ai-net
    depends_on:
      - data-profiler-api
  data-preparation-imputation:
    build:
      context: ./data-preparation-api
    ports:
      - "8004:8080"
    volumes:
      - ./integration_tests:/app/integration_tests
      - ./data:/app/data
    networks:
      - ai-net
    depends_on:
      - data-cleaner-api
  data-preparation-leakage:
    build:
      context: ./data-preparation-api
    ports:
      - "8004:8080"
    volumes:
      - ./integration_tests:/app/integration_tests
      - ./data:/app/data
    networks:
      - ai-net
    depends_on:
      - data-preparation-imputation
  data-preparation-features:
    build:
      context: ./data-preparation-api
    ports:
      - "8004:8080"
    volumes:
      - ./integration_tests:/app/integration_tests
      - ./data:/app/data
    networks:
      - ai-net
    depends_on:
      - data-preparation-leakage
networks:
  ai-net:
    driver: bridge

