jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Compose
        run: |
          docker-compose --version

      - name: Build and start all services
        run: docker-compose up -d --build

      - name: Wait for APIs to start
        run: sleep 10

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run integration tests
        run: python integration_tests/test_pipeline.py

      - name: Tear down
        run: docker-compose down
